language: java
os:
  - osx
  - linux
  - windows

jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea


after_success:
  - mvn clean test jacoco:report
  - bash <(curl -s https://codecov.io/bash) -t 187da4be-aeee-4681-ae78-e199dce98794